### ISSUE TITLE
Block number is not assignable to type 'string'

### ISSUE THREAD

**Issue by MonikaCat** [forbole/big-dipper-celo-client#35]
The error shows that block number is not assignable to type 'string' 

![Screenshot 2020-07-30 at 3 29 01 PM](https://user-images.githubusercontent.com/37407870/88894775-041c5f00-d27b-11ea-82f0-3e325e68e309.png)

**Comment by kwunyeung** [comment]
@MonikaCat please resolve conflict and merge.
