### ISSUE TITLE
The block time should be a component keep updating 

### ISSUE THREAD

**Issue by kwunyeung** [forbole/big-dipper-celo-client#57]
Currently the time won't change until a new query result is retrieved.

![image](https://user-images.githubusercontent.com/932636/89427139-7e624d00-d76d-11ea-98bf-0d3051b427ec.png)

The time should change every second if it's less than 1 minute.

**Comment by MonikaCat** [comment]
After updating the project to new UI, the timestamp should be displayed in format `DD MMMM YYYY, h:mm:ss`

![Screenshot 2020-11-06 at 3 32 05 PM](https://user-images.githubusercontent.com/37407870/98338917-df880e00-2045-11eb-8653-7290c6651fee.png)
